export const SET_RESET_SEARCH = "SET_RESET_SEARCH";

export const SET_CURRENT_SEARCH = "SET_CURRENT_SEARCH";

export const SET_FETCHED_DATA = "SET_FETCHED_DATA";
export const SET_FETCHED_DATA_SUCCESS = "SET_FETCHED_DATA_SUCCESS";
export const SET_FETCHED_DATA_FAILED = "SET_FETCHED_DATA_FAILED";

export const SET_CATEGORY = "SET_CATEGORY";

export const SET_PROVINCE = "SET_PROVINCE";

export const SET_PRICE = "SET_PRICE";

export const SET_SUBCATEGORY = "SET_SUBCATEGORY";

export const SET_PRODUCTS = "SET_PRODUCTS";

export const SET_SUBCATEGORIES = "SET_SUBCATEGORIES";
